site:
  title: AcreetionOS Docs
  url: https://docs.acreetionos.org
  robots: allow
  start_page: wiki::welcome.adoc
  keys:
    google_analytics: false
urls:
  redirect_facility: static
runtime:
  fetch: false
  log:
    failure_level: warn
content:
  sources:
    - url: .
      branches: HEAD
      start_path: components/wiki
      edit_url: https://github.com/AcreetionOS-Code/docs/edit/main/components/wiki/{path}
    - url: .
      branches: HEAD
      start_path: components/install-guide
      edit_url: https://github.com/AcreetionOS-Code/docs/edit/main/components/install-guide/{path}
    - url: .
      branches: HEAD
      start_path: components/admin-guide
      edit_url: https://github.com/AcreetionOS-Code/docs/edit/main/components/admin-guide/{path}
    - url: .
      branches: HEAD
      start_path: components/release-notes
      edit_url: https://github.com/AcreetionOS-Code/docs/edit/main/components/release-notes/{path}
    - url: .
      branches: HEAD
      start_path: components/editions
      edit_url: https://github.com/AcreetionOS-Code/docs/edit/main/components/editions/{path}
    - url: .
      branches: HEAD
      start_path: components/contributor
      edit_url: https://github.com/AcreetionOS-Code/docs/edit/main/components/contributor/{path}
antora:
  extensions:
    - require: '@antora/lunr-extension'
      index_latest_only: true
ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true
output:
  dir: ./public
